//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAW_inspecteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAW_inspecteur()
        {
            this.Inspecteur = new HashSet<Inspecteur>();
            this.Telefoonnummer_inspecteur = new HashSet<Telefoonnummer_inspecteur>();
        }
    
        public int ID { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
        public string Postcode { get; set; }
        public string Huisnummer { get; set; }
        public System.DateTime Geboortedatum { get; set; }
        public string IBAN { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspecteur> Inspecteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefoonnummer_inspecteur> Telefoonnummer_inspecteur { get; set; }
    }
}
