//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefoonnummer_inspecteur
    {
        public string Telefoonnummer { get; set; }
        public int NAW_Inspecteur_ID { get; set; }
    
        public virtual NAW_inspecteur NAW_inspecteur { get; set; }
    }
}
