//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vragenlijst_bijlage
    {
        public int Bijlage_ID { get; set; }
        public int Vragenlijst_ID { get; set; }
        public byte[] FileBytes { get; set; }
        public string MimeType { get; set; }
    
        public virtual Bijlagevraag Bijlagevraag { get; set; }
        public virtual Vragenlijst Vragenlijst { get; set; }
    }
}
