//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vragenlijst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vragenlijst()
        {
            this.Inspectie_Wel_Ingevuld_Vragenlijst = new HashSet<Inspectie_Wel_Ingevuld_Vragenlijst>();
            this.Kaartvraag_vragenlijst = new HashSet<Kaartvraag_vragenlijst>();
            this.Meerkeuzevraag_vragenlijst = new HashSet<Meerkeuzevraag_vragenlijst>();
            this.Openvraag_vragenlijst = new HashSet<Openvraag_vragenlijst>();
            this.Tabelvraag_vragenlijst = new HashSet<Tabelvraag_vragenlijst>();
            this.Template = new HashSet<Template>();
            this.Vragenlijst_bijlage = new HashSet<Vragenlijst_bijlage>();
            this.Inspectie = new HashSet<Inspectie>();
        }
    
        public int ID { get; set; }
        public string Titel { get; set; }
        public string Versie { get; set; }
        public Nullable<int> Template_ID { get; set; }
        public string Opmerking { get; set; }
        public bool Is_Ingevuld { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie_Wel_Ingevuld_Vragenlijst> Inspectie_Wel_Ingevuld_Vragenlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaartvraag_vragenlijst> Kaartvraag_vragenlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meerkeuzevraag_vragenlijst> Meerkeuzevraag_vragenlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Openvraag_vragenlijst> Openvraag_vragenlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabelvraag_vragenlijst> Tabelvraag_vragenlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Template> Template { get; set; }
        public virtual Template Template1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vragenlijst_bijlage> Vragenlijst_bijlage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie> Inspectie { get; set; }
    }
}
