//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Werknemer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Werknemer()
        {
            this.Planning_werknemer = new HashSet<Planning_werknemer>();
            this.Inspectie = new HashSet<Inspectie>();
        }
    
        public int ID { get; set; }
        public string Rol { get; set; }
        public string Username { get; set; }
        public string Wachtwoord { get; set; }
        public int NAW { get; set; }
        public bool Actief { get; set; }
    
        public virtual NAW_werknemer NAW_werknemer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planning_werknemer> Planning_werknemer { get; set; }
        public virtual Rol_werknemer Rol_werknemer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie> Inspectie { get; set; }
    }
}
