//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afspraak
    {
        public string ID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Contactpersoon_ID { get; set; }
    
        public virtual Contactpersoon Contactpersoon { get; set; }
    }
}
