//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectie_Wel_Ingevuld_Vragenlijst
    {
        public string Inspectienummer { get; set; }
        public string Vragenlijst_ID { get; set; }
        public string Inspecteur_ID { get; set; }
    
        public virtual Inspecteur Inspecteur { get; set; }
        public virtual Inspectie Inspectie { get; set; }
        public virtual Vragenlijst Vragenlijst { get; set; }
    }
}
