//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaartvraag_vragenlijst
    {
        public int Vragenlijst_ID { get; set; }
        public int Kaartvraag_ID { get; set; }
        public string Filepath_Antwoord { get; set; }
        public string Opmerking { get; set; }
        public int Positie { get; set; }
    
        public virtual Kaartvraag Kaartvraag { get; set; }
        public virtual Vragenlijst Vragenlijst { get; set; }
    }
}
