//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FestiSpecEntities : DbContext
    {
        public FestiSpecEntities()
            : base("name=FestiSpecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afspraak> Afspraak { get; set; }
        public virtual DbSet<Beschikbaarheid> Beschikbaarheid { get; set; }
        public virtual DbSet<Bijlagevraag> Bijlagevraag { get; set; }
        public virtual DbSet<Bijlagevraag_Vragenlijst> Bijlagevraag_Vragenlijst { get; set; }
        public virtual DbSet<Certificaat> Certificaat { get; set; }
        public virtual DbSet<Contactpersoon> Contactpersoon { get; set; }
        public virtual DbSet<Inspecteur> Inspecteur { get; set; }
        public virtual DbSet<Inspectie> Inspectie { get; set; }
        public virtual DbSet<Inspectie_Rapportage> Inspectie_Rapportage { get; set; }
        public virtual DbSet<Inspectie_Wel_Ingevuld_Vragenlijst> Inspectie_Wel_Ingevuld_Vragenlijst { get; set; }
        public virtual DbSet<Kaartvraag> Kaartvraag { get; set; }
        public virtual DbSet<Kaartvraag_vragenlijst> Kaartvraag_vragenlijst { get; set; }
        public virtual DbSet<Klant> Klant { get; set; }
        public virtual DbSet<Locatie> Locatie { get; set; }
        public virtual DbSet<Meerkeuzevraag> Meerkeuzevraag { get; set; }
        public virtual DbSet<Meerkeuzevraag_antwoord> Meerkeuzevraag_antwoord { get; set; }
        public virtual DbSet<Meerkeuzevraag_vragenlijst> Meerkeuzevraag_vragenlijst { get; set; }
        public virtual DbSet<NAW_inspecteur> NAW_inspecteur { get; set; }
        public virtual DbSet<NAW_Klant> NAW_Klant { get; set; }
        public virtual DbSet<NAW_werknemer> NAW_werknemer { get; set; }
        public virtual DbSet<Offerte> Offerte { get; set; }
        public virtual DbSet<Openvraag> Openvraag { get; set; }
        public virtual DbSet<Openvraag_vragenlijst> Openvraag_vragenlijst { get; set; }
        public virtual DbSet<Planning_werknemer> Planning_werknemer { get; set; }
        public virtual DbSet<Rol_werknemer> Rol_werknemer { get; set; }
        public virtual DbSet<Tabelvraag> Tabelvraag { get; set; }
        public virtual DbSet<Tabelvraag_antwoord> Tabelvraag_antwoord { get; set; }
        public virtual DbSet<Tabelvraag_vragenlijst> Tabelvraag_vragenlijst { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<Verzoek> Verzoek { get; set; }
        public virtual DbSet<Vragenlijst> Vragenlijst { get; set; }
        public virtual DbSet<Werknemer> Werknemer { get; set; }
    }
}
