//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Openvraag_vragenlijst
    {
        public string Vragenlijst_ID { get; set; }
        public string Openvraag_ID { get; set; }
        public string Antwoord { get; set; }
        public string Positie { get; set; }
    
        public virtual Openvraag Openvraag { get; set; }
        public virtual Vragenlijst Vragenlijst { get; set; }
    }
}
