//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefoonnummer
    {
        public string Telefoonnummer1 { get; set; }
        public int NAW_Werknemer_ID { get; set; }
    
        public virtual NAW_werknemer NAW_werknemer { get; set; }
    }
}
