//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vereiste_certificaten
    {
        public int Inspectienummer { get; set; }
        public int Certificaat_ID { get; set; }
    
        public virtual Inspectie Inspectie { get; set; }
    }
}
