//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiSpec.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Beschikbaarheid
    {
        public int ID { get; set; }
        [Required]
        public int Inspecteur_ID { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public System.DateTime Datum { get; set; }
    
        public virtual Inspecteur Inspecteur { get; set; }
    }
}
