//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Festispec_WPF/Beschikbaarheid.cs
namespace Festispec_WPF
=======
namespace FestiSpec.Domain.Model
>>>>>>> developer:FestiSpec.Domain/Model/Beschikbaarheid.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beschikbaarheid
    {
        public int ID { get; set; }
        public int Inspecteur_ID { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Inspecteur Inspecteur { get; set; }
    }
}
