//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiSpec.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectie_Rapportage
    {
        public int ID { get; set; }
        public string Titel { get; set; }
        public byte[] PDF { get; set; }
        public int Inspectienummer { get; set; }
    
        public virtual Inspectie Inspectie { get; set; }
    }
}
