//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FestiSpec.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspecteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspecteur()
        {
            this.Beschikbaarheid = new HashSet<Beschikbaarheid>();
            this.Inspectie_Wel_Ingevuld_Vragenlijst = new HashSet<Inspectie_Wel_Ingevuld_Vragenlijst>();
            this.Certificaat = new HashSet<Certificaat>();
            this.Inspectie = new HashSet<Inspectie>();
        }
    
        [Key]
        public int ID { get; set; }

        [DisplayName("Gebruikersnaam")]
        [Required]
        public string Username { get; set; }

        [DisplayName("Wachtwoord")]
        [Required]
        public string Wachtwoord { get; set; }

        public int NAW { get; set; }
        public bool Actief { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beschikbaarheid> Beschikbaarheid { get; set; }
        public virtual NAW_inspecteur NAW_inspecteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie_Wel_Ingevuld_Vragenlijst> Inspectie_Wel_Ingevuld_Vragenlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificaat> Certificaat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie> Inspectie { get; set; }
    }
}
