//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Festispec_WPF/Inspectie_Rapportage.cs
namespace Festispec_WPF
=======
namespace FestiSpec.Domain.Model
>>>>>>> developer:FestiSpec.Domain/Model/Inspectie_Rapportage.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectie_Rapportage
    {
        public int ID { get; set; }
        public string Titel { get; set; }
        public string Text { get; set; }
        public int Inspectienummer { get; set; }
    
        public virtual Inspectie Inspectie { get; set; }
    }
}
