//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Festispec_WPF/Kaartvraag.cs
namespace Festispec_WPF
=======
namespace FestiSpec.Domain.Model
>>>>>>> developer:FestiSpec.Domain/Model/Kaartvraag.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaartvraag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kaartvraag()
        {
            this.Kaartvraag_vragenlijst = new HashSet<Kaartvraag_vragenlijst>();
        }
    
        public int ID { get; set; }
        public string Vraag { get; set; }
        public byte[] FileBytes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaartvraag_vragenlijst> Kaartvraag_vragenlijst { get; set; }
    }
}
