//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace FestiSpec.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAW_inspecteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAW_inspecteur()
        {
            this.Inspecteur = new HashSet<Inspecteur>();
        }
    
        [Key]
        public int ID { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(30)]
        public string Voornaam { get; set; }

        public string Tussenvoegsel { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(30)]
        public string Achternaam { get; set; }

        [Required]
        [MinLength(4)]
        [MaxLength(6)]
        public string Postcode { get; set; }

        [Required]
        [MaxLength(6)]
        public string Huisnummer { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(30)]
        public string Straatnaam { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public System.DateTime Geboortedatum { get; set; }

        [Required]
        [MinLength(10)]
        [MaxLength(35)]
        public string IBAN { get; set; }
        
        [Required]
        [MinLength(5)]
        [MaxLength(35)]
        public string Email { get; set; }

        [Required]
        [MinLength(2)]
        [MaxLength(15)]
        public string Telefoonnummer { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspecteur> Inspecteur { get; set; }
    }
}
