//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Festispec_WPF/NAW_werknemer.cs
namespace Festispec_WPF
=======
namespace FestiSpec.Domain.Model
>>>>>>> developer:FestiSpec.Domain/Model/NAW_werknemer.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAW_werknemer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAW_werknemer()
        {
            this.Werknemer = new HashSet<Werknemer>();
        }
    
        public int ID { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
        public string Postcode { get; set; }
        public string Huisnummer { get; set; }
        public string Straatnaam { get; set; }
        public System.DateTime GeboorteDatum { get; set; }
        public string IBAN { get; set; }
        public string Email { get; set; }
        public string Telefoonnummer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Werknemer> Werknemer { get; set; }
    }
}
