//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Festispec_WPF/Offerte.cs
namespace Festispec_WPF
=======
namespace FestiSpec.Domain.Model
>>>>>>> developer:FestiSpec.Domain/Model/Offerte.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offerte
    {
        public int ID { get; set; }
        public int Verzoek_ID { get; set; }
        public System.DateTime Datum { get; set; }
        public decimal Bedrag { get; set; }
        public string Tekst { get; set; }
    
        public virtual Verzoek Verzoek { get; set; }
    }
}
