//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestiSpec.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabelvraag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabelvraag()
        {
            this.Tabelvraag_antwoord = new HashSet<Tabelvraag_antwoord>();
            this.Tabelvraag_vragenlijst = new HashSet<Tabelvraag_vragenlijst>();
        }
    
        public int ID { get; set; }
        public string Vraag { get; set; }
        public string VraagKop { get; set; }
        public string AntwoordKop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabelvraag_antwoord> Tabelvraag_antwoord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabelvraag_vragenlijst> Tabelvraag_vragenlijst { get; set; }
    }
}
