//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Festispec_WPF/Tabelvraag_antwoord.cs
namespace Festispec_WPF
=======
namespace FestiSpec.Domain.Model
>>>>>>> developer:FestiSpec.Domain/Model/Tabelvraag_antwoord.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabelvraag_antwoord
    {
        public int Tabelvraag_ID { get; set; }
        public string Situatie { get; set; }
        public string Antwoord { get; set; }
        public int Vragenlijst_ID { get; set; }
    
        public virtual Tabelvraag Tabelvraag { get; set; }
    }
}
