//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD:Festispec_WPF/Template.cs
namespace Festispec_WPF
=======
namespace FestiSpec.Domain.Model
>>>>>>> developer:FestiSpec.Domain/Model/Template.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template()
        {
            this.Vragenlijst1 = new HashSet<Vragenlijst>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public int Vragenlijst_ID { get; set; }
    
        public virtual Vragenlijst Vragenlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vragenlijst> Vragenlijst1 { get; set; }
    }
}
